In [ ]:
import pandas as pd

sheet_id = "1NOmVVECrN8BJQ-ZAAjpWt0Hbmd2hNCg5"
url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv"

df = pd.read_csv(url)
df.head()

,Unnamed: 0,id,date,brand,region,clean_content,lang
0,0,9253,2025-03-04 13:44:28,Wana,Jijel,why does tethering fail,en
1,1,11064,2024-12-07 10:39:28,Djezzy,Ain Temouchent,working fine today thumbs up djezzy,en
2,2,7202,2024-12-04 14:28:28,Ooredoo,Mostaganem,why does tethering fail,en
3,3,16041,2025-01-30 2:52:29,Ooredoo,Ghardaia,test speed 02 mbps in ghardaya,en
4,4,18897,2025-10-13 1:14:29,Ooredoo,missing,test speed 02 mbps in eloued,en

In [ ]:
df.columns

Index(['Unnamed: 0', 'id', 'date', 'brand', 'region', 'clean_content', 'lang'], dtype='object')

In [ ]:
df.drop(columns = ["Unnamed: 0" , "id"])

,date,brand,region,clean_content,lang
0,2025-03-04 13:44:28,Wana,Jijel,why does tethering fail,en
1,2024-12-07 10:39:28,Djezzy,Ain Temouchent,working fine today thumbs up djezzy,en
2,2024-12-04 14:28:28,Ooredoo,Mostaganem,why does tethering fail,en
3,2025-01-30 2:52:29,Ooredoo,Ghardaia,test speed 02 mbps in ghardaya,en
4,2025-10-13 1:14:29,Ooredoo,missing,test speed 02 mbps in eloued,en
...,...,...,...,...,...
12057,2025-01-01 18:02:28,Djezzy,El Oued,why am i charged for sms i never sent httpssup...,en
12058,2025-01-01 3:20:28,Ooredoo,El Oued,no service since morning ooredoo,en
12059,2024-10-19 16:43:28,Mobilis,Biskra,app login fails with error code 403,en
12060,2025-07-25 10:30:29,Mobilis,Setif,app asks for permission every open,en
12061,2024-12-19 7:39:28,TelecomDZ,Annaba,app says update required but play store shows ...,en

In [ ]:
df = df.rename(columns ={"clean_content":"content"})

# sentiment analysis (multiling)

In [ ]:
df.columns

Index(['Unnamed: 0', 'id', 'date', 'brand', 'region', 'content', 'lang'], dtype='object')

In [ ]:
!pip install -q transformers tqdm torch

from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline
from tqdm import tqdm
import pandas as pd
import torch

# Make sure GPU is available
device = 0 if torch.cuda.is_available() else -1
print(f"Using device: {'GPU' if device == 0 else 'CPU'}")

# Load model (fast tokenizer works fine here)
model_name = "cardiffnlp/twitter-xlm-roberta-base-sentiment"

tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

sentiment_model = pipeline(
    "sentiment-analysis",
    model=model,
    tokenizer=tokenizer,
    device=device,
    truncation=True,
    max_length=512,
    batch_size=16,
)



# Convert to list
texts = df['content'].astype(str).tolist()

# Run inference
results = []
for i in tqdm(range(0, len(texts), 32)):
    batch = texts[i:i+32]
    results.extend(sentiment_model(batch))

# Store results
df["sent_label"] = [r["label"] for r in results]
df["sent_score"] = [r["score"] for r in results]

df.head()

Using device: GPU

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/841 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/150 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

Device set to use cuda:0

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

  0%|          | 0/377 [00:00<?, ?it/s]
  0%|          | 1/377 [00:00<04:07,  1.52it/s]
  1%|          | 3/377 [00:00<01:23,  4.45it/s]
  1%|▏         | 5/377 [00:00<00:55,  6.73it/s]
  2%|▏         | 7/377 [00:01<00:58,  6.29it/s]
  2%|▏         | 9/377 [00:01<00:52,  7.01it/s]
  3%|▎         | 10/377 [00:01<00:51,  7.18it/s]You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

  3%|▎         | 11/377 [00:01<00:50,  7.23it/s]
  3%|▎         | 13/377 [00:02<00:46,  7.83it/s]
  4%|▎         | 14/377 [00:02<00:51,  7.01it/s]
  4%|▍         | 15/377 [00:02<00:52,  6.88it/s]
  4%|▍         | 16/377 [00:02<00:57,  6.25it/s]
  5%|▍         | 17/377 [00:02<01:00,  5.98it/s]
  5%|▍         | 18/377 [00:02<00:59,  5.99it/s]
  5%|▌         | 19/377 [00:03<00:55,  6.47it/s]
  5%|▌         | 20/377 [00:03<00:55,  6.45it/s]
  6%|▌         | 21/377 [00:03<00:52,  6.72it/s]
  6%|▌         | 22/377 [00:03<00:51,  6.84it/s]
  6%|▌         | 23/377 [00:03<00:55,  6.35it/s]
  6%|▋         | 24/377 [00:03<00:55,  6.34it/s]
  7%|▋         | 25/377 [00:03<00:54,  6.43it/s]
  7%|▋         | 26/377 [00:04<00:55,  6.37it/s]
  7%|▋         | 27/377 [00:04<00:54,  6.44it/s]
  7%|▋         | 28/377 [00:04<00:52,  6.62it/s]
  8%|▊         | 29/377 [00:04<00:53,  6.55it/s]
  8%|▊         | 31/377 [00:04<00:51,  6.69it/s]
  8%|▊         | 32/377 [00:05<00:49,  6.94it/s]
  9%|▉         | 33/377 [00:05<00:50,  6.78it/s]
  9%|▉         | 34/377 [00:05<00:47,  7.27it/s]
 10%|▉         | 36/377 [00:05<00:39,  8.54it/s]
 10%|▉         | 37/377 [00:05<00:39,  8.70it/s]
 10%|█         | 39/377 [00:05<00:34,  9.67it/s]
 11%|█         | 40/377 [00:05<00:37,  8.96it/s]
 11%|█         | 41/377 [00:05<00:36,  9.08it/s]
 11%|█▏        | 43/377 [00:06<00:34,  9.79it/s]
 12%|█▏        | 45/377 [00:06<00:32, 10.14it/s]
 12%|█▏        | 47/377 [00:06<00:30, 10.86it/s]
 13%|█▎        | 49/377 [00:06<00:34,  9.40it/s]
 14%|█▎        | 51/377 [00:06<00:32, 10.16it/s]
 14%|█▍        | 53/377 [00:07<00:30, 10.63it/s]
 15%|█▍        | 55/377 [00:07<00:27, 11.80it/s]
 15%|█▌        | 57/377 [00:07<00:24, 13.28it/s]
 16%|█▌        | 59/377 [00:07<00:30, 10.47it/s]
 16%|█▌        | 61/377 [00:07<00:27, 11.67it/s]
 17%|█▋        | 64/377 [00:07<00:21, 14.42it/s]
 18%|█▊        | 66/377 [00:08<00:21, 14.66it/s]
 18%|█▊        | 68/377 [00:08<00:20, 15.08it/s]
 19%|█▉        | 71/377 [00:08<00:17, 17.74it/s]
 20%|█▉        | 74/377 [00:08<00:17, 17.52it/s]
 20%|██        | 76/377 [00:08<00:16, 17.81it/s]
 21%|██        | 78/377 [00:08<00:18, 16.53it/s]
 21%|██        | 80/377 [00:08<00:17, 16.73it/s]
 22%|██▏       | 82/377 [00:08<00:19, 14.92it/s]
 23%|██▎       | 85/377 [00:09<00:16, 17.61it/s]
 23%|██▎       | 88/377 [00:09<00:14, 19.28it/s]
 24%|██▍       | 91/377 [00:09<00:13, 21.03it/s]
 25%|██▍       | 94/377 [00:09<00:12, 21.87it/s]
 26%|██▌       | 97/377 [00:09<00:12, 23.03it/s]
 27%|██▋       | 100/377 [00:09<00:11, 24.10it/s]
 27%|██▋       | 103/377 [00:09<00:11, 24.81it/s]
 28%|██▊       | 106/377 [00:09<00:10, 25.64it/s]
 29%|██▉       | 109/377 [00:10<00:10, 25.46it/s]
 30%|██▉       | 112/377 [00:10<00:10, 25.75it/s]
 31%|███       | 115/377 [00:10<00:10, 25.99it/s]
 31%|███▏      | 118/377 [00:10<00:09, 26.25it/s]
 32%|███▏      | 121/377 [00:10<00:09, 26.10it/s]
 33%|███▎      | 124/377 [00:10<00:09, 26.30it/s]
 34%|███▎      | 127/377 [00:10<00:09, 25.97it/s]
 34%|███▍      | 130/377 [00:10<00:09, 26.40it/s]
 35%|███▌      | 133/377 [00:10<00:09, 26.38it/s]
 36%|███▌      | 136/377 [00:11<00:09, 25.98it/s]
 37%|███▋      | 139/377 [00:11<00:12, 18.81it/s]
 38%|███▊      | 142/377 [00:11<00:13, 16.84it/s]
 38%|███▊      | 145/377 [00:11<00:12, 19.19it/s]
 39%|███▉      | 148/377 [00:11<00:10, 21.10it/s]
 40%|████      | 151/377 [00:11<00:10, 22.53it/s]
 41%|████      | 154/377 [00:11<00:09, 23.64it/s]
 42%|████▏     | 157/377 [00:12<00:08, 24.72it/s]
 42%|████▏     | 160/377 [00:12<00:08, 25.59it/s]
 43%|████▎     | 163/377 [00:12<00:08, 26.10it/s]
 44%|████▍     | 166/377 [00:12<00:08, 25.54it/s]
 45%|████▍     | 169/377 [00:12<00:08, 25.99it/s]
 46%|████▌     | 172/377 [00:12<00:07, 25.95it/s]
 46%|████▋     | 175/377 [00:12<00:07, 26.47it/s]
 47%|████▋     | 178/377 [00:12<00:07, 26.77it/s]
 48%|████▊     | 181/377 [00:12<00:07, 27.09it/s]
 49%|████▉     | 184/377 [00:13<00:07, 27.28it/s]
 50%|████▉     | 187/377 [00:13<00:07, 26.92it/s]
 50%|█████     | 190/377 [00:13<00:06, 27.18it/s]
 51%|█████     | 193/377 [00:13<00:07, 25.90it/s]
 52%|█████▏    | 196/377 [00:13<00:06, 26.29it/s]
 53%|█████▎    | 199/377 [00:13<00:06, 26.26it/s]
 54%|█████▎    | 202/377 [00:13<00:06, 26.88it/s]
 54%|█████▍    | 205/377 [00:13<00:06, 26.28it/s]
 55%|█████▌    | 208/377 [00:14<00:06, 25.69it/s]
 56%|█████▌    | 211/377 [00:14<00:06, 25.19it/s]
 57%|█████▋    | 214/377 [00:14<00:06, 25.07it/s]
 58%|█████▊    | 217/377 [00:14<00:06, 25.17it/s]
 58%|█████▊    | 220/377 [00:14<00:06, 25.03it/s]
 59%|█████▉    | 223/377 [00:14<00:06, 24.67it/s]
 60%|█████▉    | 226/377 [00:14<00:05, 25.72it/s]
 61%|██████    | 229/377 [00:14<00:05, 26.50it/s]
 62%|██████▏   | 232/377 [00:14<00:05, 26.59it/s]
 62%|██████▏   | 235/377 [00:15<00:05, 26.46it/s]
 63%|██████▎   | 238/377 [00:15<00:05, 26.09it/s]
 64%|██████▍   | 241/377 [00:15<00:07, 18.33it/s]
 65%|██████▍   | 244/377 [00:15<00:08, 15.07it/s]
 65%|██████▌   | 246/377 [00:15<00:09, 14.53it/s]
 66%|██████▌   | 248/377 [00:16<00:08, 15.41it/s]
 66%|██████▋   | 250/377 [00:16<00:08, 15.21it/s]
 67%|██████▋   | 252/377 [00:16<00:09, 13.18it/s]
 67%|██████▋   | 254/377 [00:16<00:09, 13.39it/s]
 68%|██████▊   | 256/377 [00:16<00:09, 13.33it/s]
 69%|██████▊   | 259/377 [00:16<00:07, 15.73it/s]
 69%|██████▉   | 262/377 [00:16<00:06, 18.29it/s]
 70%|███████   | 265/377 [00:17<00:05, 19.77it/s]
 71%|███████   | 268/377 [00:17<00:05, 20.99it/s]
 72%|███████▏  | 271/377 [00:17<00:04, 21.94it/s]
 73%|███████▎  | 274/377 [00:17<00:04, 22.82it/s]
 73%|███████▎  | 277/377 [00:17<00:04, 23.60it/s]
 74%|███████▍  | 280/377 [00:17<00:04, 23.47it/s]
 75%|███████▌  | 283/377 [00:17<00:03, 23.63it/s]
 76%|███████▌  | 286/377 [00:17<00:03, 24.23it/s]
 77%|███████▋  | 289/377 [00:17<00:03, 24.34it/s]
 77%|███████▋  | 292/377 [00:18<00:03, 24.02it/s]
 78%|███████▊  | 295/377 [00:18<00:03, 23.50it/s]
 79%|███████▉  | 298/377 [00:18<00:03, 23.76it/s]
 80%|███████▉  | 301/377 [00:18<00:03, 23.06it/s]
 81%|████████  | 304/377 [00:18<00:03, 22.86it/s]
 81%|████████▏ | 307/377 [00:18<00:03, 21.61it/s]
 82%|████████▏ | 310/377 [00:18<00:03, 21.51it/s]
 83%|████████▎ | 313/377 [00:19<00:02, 22.72it/s]
 84%|████████▍ | 316/377 [00:19<00:02, 23.72it/s]
 85%|████████▍ | 319/377 [00:19<00:02, 23.69it/s]
 85%|████████▌ | 322/377 [00:19<00:02, 24.35it/s]
 86%|████████▌ | 325/377 [00:19<00:02, 24.33it/s]
 87%|████████▋ | 328/377 [00:19<00:02, 24.46it/s]
 88%|████████▊ | 331/377 [00:19<00:01, 24.58it/s]
 89%|████████▊ | 334/377 [00:19<00:01, 24.57it/s]
 89%|████████▉ | 337/377 [00:20<00:01, 25.14it/s]
 90%|█████████ | 340/377 [00:20<00:01, 26.00it/s]
 91%|█████████ | 343/377 [00:20<00:01, 26.09it/s]
 92%|█████████▏| 346/377 [00:20<00:01, 26.05it/s]
 93%|█████████▎| 349/377 [00:20<00:01, 26.05it/s]
 93%|█████████▎| 352/377 [00:20<00:00, 25.96it/s]
 94%|█████████▍| 355/377 [00:20<00:00, 25.28it/s]
 95%|█████████▍| 358/377 [00:20<00:00, 25.03it/s]
 96%|█████████▌| 361/377 [00:20<00:00, 24.79it/s]
 97%|█████████▋| 364/377 [00:21<00:00, 24.83it/s]
 97%|█████████▋| 367/377 [00:21<00:00, 25.19it/s]
 98%|█████████▊| 370/377 [00:21<00:00, 25.34it/s]
 99%|█████████▉| 373/377 [00:21<00:00, 25.37it/s]
100%|██████████| 377/377 [00:21<00:00, 17.46it/s]

,Unnamed: 0,id,date,brand,region,content,lang,sent_label,sent_score
0,0,9253,2025-03-04 13:44:28,Wana,Jijel,why does tethering fail,en,negative,0.941424
1,1,11064,2024-12-07 10:39:28,Djezzy,Ain Temouchent,working fine today thumbs up djezzy,en,positive,0.847947
2,2,7202,2024-12-04 14:28:28,Ooredoo,Mostaganem,why does tethering fail,en,negative,0.941424
3,3,16041,2025-01-30 2:52:29,Ooredoo,Ghardaia,test speed 02 mbps in ghardaya,en,neutral,0.585877
4,4,18897,2025-10-13 1:14:29,Ooredoo,missing,test speed 02 mbps in eloued,en,neutral,0.686481

In [ ]:
label_map = {
    "LABEL_0": "negative",
    "LABEL_1": "neutral",
    "LABEL_2": "positive"
}
df["sent_label"] = df["sent_label"].map(label_map)

In [ ]:
df["sent_label"].value_counts(normalize=True)

Series([], Name: proportion, dtype: float64)

# topic modeling (multiling)

In [ ]:
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer

# multilingual MiniLM = light and good
embedding_model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")

docs = df["content"].astype(str).tolist()

topic_model = BERTopic(
    embedding_model=embedding_model,
    language="multilingual",
    verbose=True,
    min_topic_size=20
)

topics, probs = topic_model.fit_transform(docs)

df["topic_id"] = topics

2025-10-18 22:26:22,087 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/377 [00:00<?, ?it/s]

2025-10-18 22:26:28,192 - BERTopic - Embedding - Completed ✓
2025-10-18 22:26:28,193 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-10-18 22:27:22,459 - BERTopic - Dimensionality - Completed ✓
2025-10-18 22:27:22,461 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-10-18 22:27:22,989 - BERTopic - Cluster - Completed ✓
2025-10-18 22:27:22,996 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-10-18 22:27:23,167 - BERTopic - Representation - Completed ✓

In [ ]:
# get top words for each topic
topic_info = topic_model.get_topic_info()
topic_info.head()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,827,-1_144p_only_streaming_entering,"[144p, only, streaming, entering, near, buildi...",[signal lost when entering building near boume...
1,0,227,0_speed_high_latency_data,"[speed, high, latency, data, low, ok, fine, bu...","[data speed fine but latency high in tipaza, d..."
2,1,218,1_fixed_it_team_impressed,"[fixed, it, team, impressed, fast, the, contac...","[the team fixed it fast impressed, the team fi..."
3,2,217,2_midcall_connection_mom_sad,"[midcall, connection, mom, sad, lost, with, co...","[lost connection midcall with mom sad, lost co..."
4,3,215,3_still_applied_promo_billing,"[still, applied, promo, billing, wrong, but, ,...","[promo applied but billing still wrong, promo ..."

In [ ]:
def get_topic_label(tid):
    if tid == -1:
        return "other"
    top_words = [word for word, _ in topic_model.get_topic(tid)[:3]]
    return ", ".join(top_words)

df["topic_name"] = df["topic_id"].apply(get_topic_label)

In [ ]:
df["topic_name"].value_counts().head(10)

topic_name
other                        827
speed, high, latency         227
fixed, it, team              218
midcall, connection, mom     217
still, applied, promo        215
crash, 500, error            212
make, help, cant             212
promos, bad, good            211
recharge, billing, failed    207
sent, never, am              206
Name: count, dtype: int64

In [ ]:
df[df["sent_label"]=="negative"]["topic_name"].value_counts().head(10)

Series([], Name: count, dtype: int64)

In [ ]:
# save df

In [ ]:
df.to_csv("feedback_with_sentiment_topics.csv", index=False)
print(" Saved with sentiment and topic columns.")

 Saved with sentiment and topic columns.